## Basic

In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [3]:
type(x)

numpy.ndarray

In [4]:
y = np.array([[1, 3, 5], [2, 4, 6]])
y

array([[1, 3, 5],
       [2, 4, 6]])

In [5]:
type(y)

numpy.ndarray

In [6]:
z = np.array([[1, 3, 5]])
z

array([[1, 3, 5]])

In [7]:
z.shape

(1, 3)

In [8]:
x.shape

(4,)

In [9]:
z.ndim

2

In [10]:
x.ndim

1

## Data Type

In [11]:
items = [1, 2, 'text']

x = np.array(items)
x

array(['1', '2', 'text'], dtype='<U21')

In [12]:
items = [1, 2, 3.0]

y = np.array(items)
y

array([1., 2., 3.])

In [13]:
z = y.astype('int32')
z

array([1, 2, 3], dtype=int32)

## Generation

In [14]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
y = np.arange(1, 10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
z = np.arange(1, 10, 2)
z

array([1, 3, 5, 7, 9])

In [17]:
x = np.zeros((3, 2), dtype='int32')
x

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [18]:
y = np.ones((2, 3))
y

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
z = np.full((3, 2), 7)
z

array([[7, 7],
       [7, 7],
       [7, 7]])

## reshape

In [20]:
x = np.arange(1, 16)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [21]:
y = x.reshape(3,5)
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [22]:
z = x.reshape(5,3)
z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

## random

In [23]:
# rand : 0과 1사이의 uniform한 분포
x = np.random.rand(2, 3)
x

array([[0.56210516, 0.29045035, 0.7322548 ],
       [0.15446706, 0.43961565, 0.04251535]])

In [24]:
# randn : normal distribution
y = np.random.randn(2, 3)
y

array([[-0.08874598,  2.39998067,  0.61353563],
       [ 0.05580309,  0.68906431,  0.25589411]])

In [25]:
# randint : 정수
z = np.random.randint(1, 100, size=(2,3))
z

array([[96, 11, 88],
       [19, 58, 29]])

In [26]:
np.random.seed(1234)
x = np.random.randn(3, 4)
x

array([[ 0.47143516, -1.19097569,  1.43270697, -0.3126519 ],
       [-0.72058873,  0.88716294,  0.85958841, -0.6365235 ],
       [ 0.01569637, -2.24268495,  1.15003572,  0.99194602]])

In [27]:
np.random.seed(1234)
y = np.random.randn(3, 4)
y

array([[ 0.47143516, -1.19097569,  1.43270697, -0.3126519 ],
       [-0.72058873,  0.88716294,  0.85958841, -0.6365235 ],
       [ 0.01569637, -2.24268495,  1.15003572,  0.99194602]])

## Indexing

In [28]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
x[0]

0

In [30]:
x[-1]

9

In [31]:
x[3] = 100
x

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9])

In [32]:
y = np.arange(10).reshape(2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
y[1]

array([5, 6, 7, 8, 9])

In [34]:
y[0][2]

2

In [35]:
y[1, 2]

7

In [36]:
z = np.arange(10)
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
z[z > 5]

array([6, 7, 8, 9])

In [38]:
z[z == 6]

array([6])

## Slicing

In [39]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
x[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
x[:4]

array([0, 1, 2, 3])

In [42]:
x[2:4]

array([2, 3])

In [43]:
y = np.arange(10).reshape(2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
y[1:2]

array([[5, 6, 7, 8, 9]])

In [45]:
y[:,:2]

array([[0, 1],
       [5, 6]])

In [46]:
y[:, 1:4]

array([[1, 2, 3],
       [6, 7, 8]])

In [47]:
y[1:, 1]

array([6])

## Sorting

In [48]:
x = np.array([0, 6, 2, 4, 3])
x

array([0, 6, 2, 4, 3])

In [49]:
y = np.sort(x)
y

array([0, 2, 3, 4, 6])

In [50]:
x

array([0, 6, 2, 4, 3])

In [51]:
x.sort()
x

array([0, 2, 3, 4, 6])

In [52]:
x = np.array([0, 6, 2, 4, 3])
x

array([0, 6, 2, 4, 3])

In [53]:
y = np.sort(x)[::-1]
y

array([6, 4, 3, 2, 0])

In [54]:
x = np.array([[0, 6, 2], [4, 1, 2], [3, 5, 4]])
x

array([[0, 6, 2],
       [4, 1, 2],
       [3, 5, 4]])

In [55]:
y = np.sort(x, axis=0)
y

array([[0, 1, 2],
       [3, 5, 2],
       [4, 6, 4]])

In [56]:
z = np.sort(x, axis=1)
z

array([[0, 2, 6],
       [1, 2, 4],
       [3, 4, 5]])

In [57]:
x = np.array([0, 6, 2, 4, 3])
x

array([0, 6, 2, 4, 3])

In [58]:
y = np.argsort(x)
y

array([0, 2, 4, 3, 1])

In [59]:
type(y)

numpy.ndarray

In [60]:
x

array([0, 6, 2, 4, 3])

In [61]:
x[y]

array([0, 2, 3, 4, 6])

## 행렬 내적 (dot product)

In [62]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8], [9, 10], [11, 12]])

z = np.dot(x, y)
z

array([[ 58,  64],
       [139, 154]])

## 전치 행렬 (Transposed Matrix)

In [63]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
y = np.transpose(x)
y

array([[1, 4],
       [2, 5],
       [3, 6]])

## Basic Operation

In [65]:
x = np.array([[5, 6],
              [7, 8]])

y = np.array([[1, 2],
              [3, 4]])

In [66]:
z = np.add(x, y)
z

array([[ 6,  8],
       [10, 12]])

In [67]:
z = np.subtract(x, y)
z

array([[4, 4],
       [4, 4]])

In [68]:
z = np.multiply(x, y)
z

array([[ 5, 12],
       [21, 32]])

In [69]:
z = np.divide(x, y)
z

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

## Statistics

In [70]:
x = np.random.randint(1, 100, size=(2,3))
x

array([[48, 51, 77],
       [38, 35, 39]])

In [71]:
y = np.mean(x)
y

48.0

In [72]:
y = np.median(x)
y

43.5

In [73]:
y = np.max(x)
y

77

In [74]:
y = np.argmax(x)
y

2

In [75]:
y = np.var(x)
y

200.0

In [76]:
y = np.std(x)
y

14.142135623730951

In [77]:
y = np.sum(x)
y

288

In [78]:
y = np.cumsum(x)
y

array([ 48,  99, 176, 214, 249, 288])